import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    _id: "p1",
    name: "Set de Moños Negros con Brillos",
    slug: "set-moños-negros-brillos",
    price: 9.99,
    description: "Set de moños negros con detalles brillantes y apliques tipo strass para peinados elegantes.",
    category: "Moños",
    imageUrl: "/products/product-1.jpg",
  },
  {
    _id: "p2",
    name: "Moños Color Pastel con Osito",
    slug: "moños-colores-aplique-osito",
    price: 14.5,
    description: "Moños de colores pastel con aplique de osito, ideales para looks divertidos y tiernos.",
    category: "Moños",
    imageUrl: "/products/product-2.jpg",
  },
  {
    _id: "p3",
    name: "Vincha Negra con Lazo y Tul",
    slug: "vincha-negra-lazo-lentejuelas",
    price: 11,
    description: "Vincha negra con lazo de tul y detalle de lentejuelas para ocasiones especiales.",
    category: "Vinchas",
    imageUrl: "/products/product-3.jpg",
  },
  {
    _id: "p4",
    name: "Set de Colitas Scrunchie Clasicas",
    slug: "set-colitas-scrunchies-clasicas",
    price: 18.75,
    description: "Set de colitas tipo scrunchie en tonos blanco, rojo y cuadriculado para uso diario.",
    category: "Colitas",
    imageUrl: "/products/product-4.jpg",
  },
  {
    _id: "p5",
    name: "Set de Posavasos x4",
    slug: "set-posavasos-x4",
    price: 7.25,
    description: "Set de 4 posavasos de corcho natural, ligeros y duraderos.",
    category: "Hogar",
    imageUrl: "/products/product-1.jpg",
  },
  {
    _id: "p6",
    name: "Botella Termica 500ml",
    slug: "botella-termica-500ml",
    price: 21.9,
    description: "Botella termica de acero inoxidable que conserva temperatura.",
    category: "Accesorios",
    imageUrl: "/products/product-2.jpg",
  },
];
